### PR TITLE
[LAKECOMP-498] Exposing scheduler configuration values s.t. they can …

### PR DESCRIPTION
**Pull request by AnnaSavarin**
…be displayed by generic /conf endpoint.  Introducing a bit more consistency to the scheduler implementations.

### CODE REVIEW

**Comment by ashangit** [comment]
+1

**Comment by MikhailErofeev** [comment]
LGTM, but checkstyle should fail on line lengths at least

**Comment by AnnaSavarin** [comment]
Thanks.  I fixed all lines to be 80 characters or less.

**Comment by AnnaSavarin** [comment]
Fixed a failing test (I misunderstood the test). Since the code is fine and the only tests that fail are the ones that fail in cdh5-2.6.0_5.11.0-criteo on my machine, and since I tested this manually, I will merge.

**Pull request merged**
