### PR TITLE
HDP-12448 backport a list of commits that block decommissionning and block report

### PR DESCRIPTION
**Pull request by mlachkar**

### CODE REVIEW

**Comment by mlachkar** [comment]
I was able to packagage each commit, but in this order.

**Comment by Willymontaz** [comment]
Seems good. But I don't get your comment "I was able to packagage each commit, but in this order.". What is the "but in this order". Is the order different than the true order of commits ?

**Comment by mlachkar** [comment]
There is no real order, since those commit are from different CDH versions (And I cherry-picked them from different versions). I think it mostly the right order (the older to the most recent).
My comment was just to tell , after every commit, I build and it succeeded.

**Comment by Willymontaz** [comment]
Does not help in the bug faced. The bug is resolved by https://github.com/criteo-forks/hadoop-common/pull/125.

Closing PR.

**Pull request closed without merging**
