### PR TITLE
YARN-2786 and YARN-2800 : Minor patches that improve the usage of yarn node labels

### PR DESCRIPTION
**Pull request by mlachkar**
… listing node-labels collection. Contributed by Wangda Tan.

### CODE REVIEW

**Review by remysaissy — APPROVED** [review]

**Review by ashangit — COMMENTED** [review]
YARN-2786 -> LGTM

**Review by ashangit — COMMENTED** [review]
YARN-2800 -> LGTM

**Comment by ashangit** [comment]
YARN-2493 -> LGTM

**Comment by ashangit** [comment]
YARN-3230 -> LGTM

**Comment by ashangit** [comment]
YARN-2920 -> LGTM

**Comment by ashangit** [comment]
YARN-3262 -> I prefer to not backport it as it is not anymore available in newer release.
Only apply below patch to hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/SchedulerApplicationAttempt.java on backport YARN-4140

```
public synchronized Collection<RMContainer> getLiveContainers() {
     return new ArrayList<RMContainer>(liveContainers.values());
   }
-  
+
+  public AppSchedulingInfo getAppSchedulingInfo() {
+    return this.appSchedulingInfo;
+  }
+
   /**
    * Is this application pending?
    * @return true if it is else false.
```

**Comment by mlachkar** [comment]
YARN-3262  removed. Thanks

**Comment by ashangit** [comment]
Global LGTM :), lets finished tests on our exp cluster and then merge it

**Pull request merged**
